services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile.prod
    command: uv run uvicorn app.main:app --reload --workers 1 --host 0.0.0.0 --port 8000
    volumes:
      - ./server:/usr/src/app
      - /usr/src/app/.venv # To isolate venv from host
    ports:
      - "8004:8000"
    environment:
      - ENVIRONMENT=dev
      - TESTING=0
      - DATABASE_URL=postgres://postgres:postgres@server-db:5432/server_dev
      - DATABASE_TEST_URL=postgres://postgres:postgres@server-db:5432/server_test
    depends_on:
      - server-db

  server-db:
    build:
      context: ./server/db
      dockerfile: Dockerfile
    expose:
      - "5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
