# compose file for Dockerfile.prod debugging purposes
# Since the app is deployed on Fly, we don't really need compose.prod.yaml

services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile.prod
    volumes:
      - /usr/src/app/.venv # To isolate venv from host
    ports:
      - "8084:8080"
    environment:
      - ENVIRONMENT=dev
      - TESTING=0
      - DATABASE_URL=postgres://postgres:postgres@server-db:5432/server_dev
      - DATABASE_TEST_URL=postgres://postgres:postgres@server-db:5432/server_test
    depends_on:
      - server-db

  server-db:
    build:
      context: ./server/db
      dockerfile: Dockerfile
    expose:
      - "5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
