FROM python:3.12.4-slim-bookworm
# Set up uv
COPY --from=ghcr.io/astral-sh/uv:0.4.9 /uv /bin/uv

# Create directory for the app user
RUN mkdir -p /home/app

# Create the app user
RUN addgroup --system app && adduser --system --group app

# Create the appropriate directories
ENV HOME=/home/app
ENV APP_HOME=/home/app/server
RUN mkdir $APP_HOME
WORKDIR $APP_HOME

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1
ENV ENVIRONMENT=prod
ENV TESTING=0

RUN apt-get update \
  && apt-get -y install netcat-traditional gcc postgresql \
  && apt-get clean

COPY ./uv.lock ./pyproject.toml ./
RUN uv sync --frozen --no-cache

COPY . . 

# chown all the files to the app user
RUN chown -R app:app $HOME

# change to the app user
USER app

CMD ["uv", "run", "gunicorn", "--bind", "0.0.0.0:8080", "app.main:app", "-k", "uvicorn.workers.UvicornWorker"]
