FROM ghcr.io/astral-sh/uv:python3.12-bookworm-slim

# Create directory for the app user
RUN mkdir -p /home/app

# Create the app user
RUN addgroup --system app && adduser --system --group app

# Create the appropriate directories
ENV HOME=/home/app
ENV APP_HOME=/home/app/server
RUN mkdir $APP_HOME
WORKDIR $APP_HOME

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1
ENV ENVIRONMENT=prod
ENV TESTING=0

RUN chown -R app:app $HOME
USER app

COPY ./uv.lock ./pyproject.toml ./
RUN --mount=type=cache,target=/root/.cache/uv \
  --mount=type=bind,source=uv.lock,target=uv.lock \
  --mount=type=bind,source=pyproject.toml,target=pyproject.toml \
  uv sync --frozen --no-install-project --no-dev

COPY --chown=app:app . . 

CMD ["uv", "run", "gunicorn", "--bind", "0.0.0.0:8080", "app.main:app", "-k", "uvicorn.workers.UvicornWorker"]
