# fly.toml app configuration file generated for tdd-fastapi on 2024-09-12T20:35:15+04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'tdd-fastapi'
primary_region = 'ams'

[build]
dockerfile = "Dockerfile.prod"

[http_service]
internal_port = 8080
force_https = true
auto_stop_machines = 'stop'
auto_start_machines = true
min_machines_running = 1
processes = ['app']

[[vm]]
size = 'shared-cpu-1x'
